<?php
/**
 * VoxVeil Question Bank
 * Contains 20 real-world based questions for each field, purpose, and status.
 */

$questionBank = [
    'fields' => [
        'BCA' => [
            "How do you stay updated with the latest trends in software development?",
            "Describe your experience with version control systems like Git.",
            "What is the most challenging bug you have ever fixed?",
            "Explain the concept of RESTful APIs to a non-technical person.",
            "What are your thoughts on the impact of AI on software engineering?",
            "How do you ensure your code is secure and follows best practices?",
            "Describe a project where you used a database. How did you design the schema?",
            "What is the difference between a framework and a library?",
            "How do you approach learning a new programming language?",
            "Explain the importance of responsive design in web development.",
            "What is your favorite IDE, and why does it help your productivity?",
            "How do you handle cross-browser compatibility issues?",
            "Describe a time you worked on a team project. How did you manage collaboration?",
            "What do you know about cloud services like AWS or Azure?",
            "How do you optimize a website for better performance?",
            "What is unit testing, and why is it important?",
            "Explain the difference between SQL and NoSQL databases.",
            "How do you handle tight deadlines in a development project?",
            "What is the most interesting technology you've explored recently?",
            "How do you handle technical debt in a long-term project?"
        ],
        'PHYSICS' => [
            "How would you explain the significance of the Higgs Boson?",
            "Describe a complex physics problem you solved using mathematical modeling.",
            "What is your understanding of quantum entanglement?",
            "How do you approach laboratory data analysis and error calculation?",
            "What role does physics play in sustainable energy solutions?",
            "Explain the laws of thermodynamics in a real-world context.",
            "How do you apply computational physics in your research or projects?",
            "Describe the importance of the Doppler effect in modern technology.",
            "What is the difference between classical and quantum mechanics?",
            "How do you handle uncertainties in experimental measurements?",
            "Explain the concept of dark matter and its role in the universe.",
            "How does general relativity affect GPS technology?",
            "What are the challenges of nuclear fusion as a power source?",
            "Describe a physics experiment you conducted. What were the results?",
            "How do you stay current with breakthroughs in physics research?",
            "What is the significance of the Large Hadron Collider?",
            "Explain the photoelectric effect and its applications.",
            "How do you simplify complex physical concepts for non-scientists?",
            "What is the role of symmetry in particle physics?",
            "How do you see the future of space exploration evolving?"
        ],
        'FOOD PROCESSING' => [
            "Explain the role of HACCP in ensuring food safety.",
            "How does dehydration affect the nutritional value of processed foods?",
            "What are the latest innovations in sustainable food packaging?",
            "Describe the process of pasteurization and its critical control points.",
            "How do you manage supply chain integrity in food production?",
            "Explain the difference between sterilization and pasteurization.",
            "How do you optimize food shelf life without using controversial additives?",
            "What are the challenges of scaling up a food recipe for mass production?",
            "Describe the impact of biotechnology on food processing.",
            "How do you ensure consistent flavor profiles in large batches?",
            "What is the importance of cold chain management in the food industry?",
            "How do you handle waste management in a food processing plant?",
            "Explain the concept of 'clean label' in the food industry.",
            "What are the regulatory requirements for food labeling in your region?",
            "How do you approach quality control in a fast-paced production line?",
            "Describe the process of extrusion in food manufacturing.",
            "What are the benefits and risks of genetically modified foods?",
            "How do you manage allergens in a multi-product facility?",
            "What is the role of sensors and IoT in modern food processing?",
            "How do you balance cost-efficiency with food quality and safety?"
        ],
        'COMMERCE' => [
            "How do you analyze a company's financial health using its balance sheet?",
            "Explain the impact of global inflation on local retail markets.",
            "What is your strategy for effective risk management in a volatile economy?",
            "How do you handle ethical dilemmas in financial reporting?",
            "What are the key drivers of consumer behavior in the digital age?",
            "Explain the concept of working capital management.",
            "How do you evaluate the feasibility of a new business venture?",
            "What is your understanding of the relationship between interest rates and investment?",
            "Describe the role of e-commerce in traditional retail transformation.",
            "How do you approach tax planning for a small to medium enterprise?",
            "What are the advantages and disadvantages of different business structures?",
            "How do you use data analytics to drive business decisions?",
            "Explain the importance of branding in a competitive market.",
            "What is your approach to negotiation in a B2B environment?",
            "How do you stay informed about changes in international trade laws?",
            "Describe a time you identified a market opportunity. How did you act on it?",
            "What are the challenges of managing a global supply chain?",
            "How do you balance short-term profits with long-term sustainability?",
            "What is the role of corporate social responsibility in modern business?",
            "How do you manage a diverse workforce in a globalized economy?"
        ],
        'ENGINEERING' => [
            "Describe a project where you had to solve a complex engineering problem.",
            "How do you ensure the safety and reliability of your designs?",
            "What is your experience with CAD software?",
            "Explain the importance of material selection in structural engineering.",
            "How do you handle project management and resource allocation?",
            "Describe a time you had to work with a multidisciplinary team.",
            "What are the challenges of implementing sustainable engineering practices?",
            "How do you approach troubleshooting a mechanical or electrical failure?",
            "Explain the concept of lean manufacturing.",
            "What is the role of automation and robotics in modern engineering?",
            "How do you stay updated with emerging engineering technologies?",
            "Describe your experience with prototyping and testing.",
            "How do you manage technical specifications and documentation?",
            "What is the impact of 3D printing on the manufacturing industry?",
            "How do you balance performance requirements with budget constraints?",
            "Explain the principles of thermodynamics in your specific field.",
            "How do you handle changes in project scope and requirements?",
            "What do you know about smart cities and their engineering challenges?",
            "Describe a time you had to explain a technical concept to a non-technical client.",
            "How do you see AI transforming the engineering design process?"
        ],
        'MEDICINE' => [
            "How do you handle high-pressure situations in a clinical setting?",
            "Describe your approach to patient-centered care.",
            "What are the challenges of staying updated with medical research?",
            "Explain the importance of ethics in medical practice.",
            "How do you handle difficult conversations with patients or their families?",
            "Describe a time you had to work with a diverse medical team.",
            "What are your thoughts on the role of technology in healthcare?",
            "How do you maintain a work-life balance in a demanding medical career?",
            "Explain the significance of preventive medicine.",
            "How do you handle errors or near-misses in a medical environment?",
            "What is your approach to diagnosing complex or rare conditions?",
            "How do you ensure clear communication with your patients?",
            "Describe the impact of telemedicine on healthcare delivery.",
            "What are the challenges of managing chronic diseases in an aging population?",
            "How do you stay informed about global health trends and outbreaks?",
            "Explain the role of genomics in personalized medicine.",
            "How do you handle burnout in the healthcare profession?",
            "What is your experience with medical record-keeping and data privacy?",
            "Describe a time you showed leadership in a clinical situation.",
            "How do you see the future of healthcare evolving with AI?"
        ],
        'ARTS' => [
            "How do you define the role of art in society?",
            "Describe your creative process for a recent project or artwork.",
            "What are the challenges of pursuing a career in the arts?",
            "Explain the importance of cultural diversity in artistic expression.",
            "How do you handle criticism and feedback on your work?",
            "Describe the impact of digital media on traditional art forms.",
            "How do you stay inspired and overcome creative blocks?",
            "What is your favorite period or movement in art history, and why?",
            "How do you balance artistic vision with commercial viability?",
            "Explain the role of storytelling in your medium.",
            "How do you use art to address social or political issues?",
            "What is the importance of networking and self-promotion in the arts?",
            "Describe a time you collaborated with other artists on a project.",
            "How do you manage your time and resources as a freelance artist?",
            "What is the future of art in the age of artificial intelligence?",
            "How do you research and gather inspiration for your work?",
            "Explain the significance of public art in urban spaces.",
            "How do you approach teaching or mentoring others in the arts?",
            "What role does technology play in your artistic practice?",
            "Describe your long-term goals as an artist or creative professional."
        ],
        'IT' => [
            "What is your experience with cloud computing and virtualization?",
            "Explain the importance of cybersecurity in a modern business environment.",
            "How do you approach network troubleshooting and performance tuning?",
            "Describe your experience with different operating systems (Windows, Linux, macOS).",
            "What are the challenges of managing a remote or distributed IT infrastructure?",
            "Explain the concept of DevOps and its benefits.",
            "How do you handle data backup and disaster recovery planning?",
            "What is your experience with database administration and optimization?",
            "Describe your approach to IT asset management and documentation.",
            "How do you stay updated with the latest cybersecurity threats?",
            "What do you know about containerization technologies like Docker and Kubernetes?",
            "How do you handle service desk escalations and user support?",
            "Explain the role of APIs in system integration.",
            "How do you approach software patch management and system updates?",
            "What is your experience with scripting and automation (Python, PowerShell, Bash)?",
            "Describe a time you implemented an IT solution that improved efficiency.",
            "How do you manage project timelines and stakeholders in an IT project?",
            "What are the challenges of migrating legacy systems to the cloud?",
            "Explain the principles of ITIL and its impact on service delivery.",
            "How do you see AI and machine learning impacting the IT landscape?"
        ],
        'FINANCE' => [
            "Explain the difference between fundamental and technical analysis.",
            "How do you evaluate the creditworthiness of a potential borrower?",
            "Describe your experience with financial modeling and forecasting.",
            "What are the challenges of managing an investment portfolio in a volatile market?",
            "Explain the concept of capital structure and its importance.",
            "How do you stay informed about changes in financial regulations?",
            "Describe your approach to risk assessment and mitigation in finance.",
            "What is your understanding of the impact of global economics on local markets?",
            "How do you handle high-pressure situations in a trading or investment environment?",
            "Explain the role of fintech in transforming traditional banking services.",
            "What is your experience with auditing and financial reporting standards (IFRS/GAAP)?",
            "Describe a time you identified a financial risk and how you handled it.",
            "How do you manage relationships with institutional and retail investors?",
            "What are the key factors you consider when performing a company valuation?",
            "Explain the concept of ESG (Environmental, Social, and Governance) in investing.",
            "How do you approach cash flow management for a large corporation?",
            "What is the role of blockchain and cryptocurrencies in the future of finance?",
            "Describe your experience with treasury management and foreign exchange risk.",
            "How do you communicate complex financial data to non-finance stakeholders?",
            "What are your thoughts on the impact of AI on financial advisory services?"
        ],
        'MARKETING' => [
            "How do you define and reach your target audience in a digital age?",
            "Describe a successful marketing campaign you were involved in.",
            "What is your experience with social media marketing and brand management?",
            "Explain the importance of SEO and SEM in modern marketing.",
            "How do you use data analytics to track and improve campaign performance?",
            "Describe your approach to content marketing and storytelling.",
            "What are the challenges of maintaining brand consistency across multiple channels?",
            "How do you stay updated with the latest trends in marketing technology?",
            "Explain the role of influencer marketing in a modern marketing strategy.",
            "How do you handle negative feedback or a PR crisis on social media?",
            "What is your experience with email marketing and lead generation?",
            "Describe a time you had to adjust a marketing strategy based on market research.",
            "How do you balance creative ideas with data-driven decision-making?",
            "What are the key metrics you use to measure marketing ROI?",
            "Explain the concept of customer lifetime value and its importance.",
            "How do you approach competitive analysis in a crowded market?",
            "What is the role of customer experience (CX) in brand loyalty?",
            "How do you manage marketing budgets and resource allocation?",
            "Describe your experience with CRM tools and marketing automation.",
            "What is the future of marketing with the rise of AI and personalization?"
        ],
        'HR' => [
            "What is your approach to recruitment and talent acquisition?",
            "Describe a time you had to handle a difficult employee relations issue.",
            "How do you manage performance review processes and feedback loops?",
            "Explain the importance of diversity, equity, and inclusion (DEI) in the workplace.",
            "How do you handle employee onboarding and offboarding procedures?",
            "Describe your experience with payroll administration and benefits management.",
            "What are the challenges of managing a remote or hybrid workforce?",
            "How do you stay informed about changes in labor laws and regulations?",
            "Explain the role of HR in fostering a positive company culture.",
            "How do you handle workplace conflicts and mediation?",
            "What is your experience with HR data analytics and reporting?",
            "Describe a time you implemented an HR initiative that improved employee engagement.",
            "How do you manage training and development programs for employees?",
            "What are the key factors in designing a competitive compensation strategy?",
            "Explain the importance of employee wellbeing and mental health support.",
            "How do you approach succession planning for key roles in the organization?",
            "What is your experience with HR software and applicant tracking systems (ATS)?",
            "Describe your approach to handling sensitive and confidential information.",
            "How do you manage change in an organization from an HR perspective?",
            "What is the future of HR in the age of AI and workforce automation?"
        ],
        'HEALTHCARE' => [
            "How do you ensure patient safety and quality of care in your facility?",
            "Describe your experience with healthcare administration and facility management.",
            "What are the challenges of staying compliant with healthcare regulations (like HIPAA)?",
            "Explain the role of electronic health records (EHR) in modern healthcare.",
            "How do you handle patient complaints and service quality issues?",
            "Describe your approach to clinical staff recruitment and retention.",
            "What are the challenges of managing healthcare costs while maintaining quality?",
            "How do you stay updated with changes in healthcare policy and insurance?",
            "Explain the importance of infection control and hospital-acquired infection prevention.",
            "How do you handle high-pressure situations in a healthcare environment?",
            "What is your experience with medical technology procurement and management?",
            "Describe a time you improved a healthcare process or service.",
            "How do you manage collaboration between different healthcare departments?",
            "What are the key factors in building a patient-centric culture?",
            "Explain the role of data analytics in improving healthcare outcomes.",
            "How do you approach disaster preparedness and emergency management in healthcare?",
            "What is your experience with telehealth and remote patient monitoring?",
            "Describe your approach to managing ethical dilemmas in a healthcare setting.",
            "How do you handle the emotional challenges of working in healthcare?",
            "What is the future of healthcare delivery with the integration of AI?"
        ],
        'EDUCATION' => [
            "What is your philosophy on student engagement and classroom management?",
            "Describe a time you had to adapt your teaching methods for a diverse group of learners.",
            "How do you use technology to enhance the learning experience?",
            "Explain the importance of assessment and feedback in the learning process.",
            "How do you handle difficult students or behavior issues in the classroom?",
            "Describe your experience with curriculum design and lesson planning.",
            "What are the challenges of managing administrative duties alongside teaching?",
            "How do you stay updated with the latest educational research and pedagogical trends?",
            "Explain the role of empathy and emotional intelligence in teaching.",
            "How do you handle parent-teacher communication and expectations?",
            "What is your experience with online and blended learning models?",
            "Describe a time you helped a student overcome a significant academic challenge.",
            "How do you manage your own professional development and growth?",
            "What are the key factors in creating an inclusive learning environment?",
            "Explain the significance of lifelong learning for both students and educators.",
            "How do you approach standardized testing and its impact on teaching?",
            "What is your experience with educational software and learning management systems (LMS)?",
            "Describe your approach to collaborating with other educators and staff.",
            "How do you manage stress and prevent burnout in the education profession?",
            "What is the future of education with the rise of AI and personalized learning?"
        ],
        'OTHER' => [
            "Tell me about a time you had to solve a unique problem at work.",
            "How do you handle shifting priorities and multitasking in your role?",
            "Describe your approach to professional development and continuous learning.",
            "What are the key qualities of a successful professional in your area?",
            "How do you ensure clear and effective communication with your colleagues?",
            "Describe a time you took the initiative on a project or task.",
            "How do you handle feedback and use it to improve your performance?",
            "What is your strategy for maintaining productivity and focus Throughout the day?",
            "Explain the importance of teamwork and collaboration in your field.",
            "How do you handle difficult or challenging situations at work?",
            "What are your career goals for the next three years?",
            "Describe a time you had to learn a new skill or technology quickly.",
            "How do you approach networking and building professional relationships?",
            "What is your experience with project management tools and techniques?",
            "How do you balance your personal life with a demanding professional role?",
            "Describe a significant achievement in your career so far.",
            "How do you handle workplace stress and maintain a positive attitude?",
            "What are the most important ethical considerations in your field?",
            "How do you see your industry evolving in the next five years?",
            "What advice would you give to someone starting out in your field?"
        ],
        'SILQ' => [
            'How does EcoRoute AI handle real-time traffic data unpredictability?',
            'Explain the mathematical foundation of your CO2 optimization algorithm.',
            'SILQ emphasizes "Engineering Excellence." How is your code tested for reliability?',
            'How would you integrate block-chain for transparent supply chain tracking in EcoRoute?',
            'What is the next major feature you would add to EcoRoute AI?',
            'How do you handle data privacy when gathering user route preferences?',
            "How do you scale the real-time processing of sensor data in SILQ?",
            "What is the core architecture design for the EcoRoute AI backend?",
            "How do you handle edge cases in carbon footprint calculation?",
            "Describe a time you improved the latency of a real-time system.",
            "What are your views on the ethical use of AI in transportation?",
            "How do you manage technical documentation in a fast-paced startup like SILQ?",
            "What is your approach to system monitoring and alerting?",
            "How do you handle API versioning for third-party integrations?",
            "Describe your experience with energy-efficient computing.",
            "How do you ensure high availability for the EcoRoute AI platform?",
            "What is the most significant technical challenge you've faced at SILQ?",
            "How do you mentor junior engineers on the importance of sustainability?",
            "What is the role of machine learning in path optimization at SILQ?",
            "How do you see SILQ contributing to global net-zero goals?"
        ]
    ],
    'purposes' => [
        'Graduation Interview' => [
            "What was the most important lesson you learned during your final year project?",
            "How has your education prepared you for the professional world?",
            "What is your plan for the first six months after you graduate?",
            "Describe a time you showed leadership in a student organization.",
            "How do you plan to continue your learning after graduation?",
            "What specific skills did you gain that make you a good fit for this company?",
            "How do you handle transitions from an academic to a corporate environment?",
            "What was your favorite subject and how does it apply to this job?",
            "Describe a time you failed in college and what you learned from it.",
            "How do you handle group conflicts in academic projects?",
            "What are your expectations from your first employer?",
            "How do you stay motivated when working on long-term assignments?",
            "What did you do during your most recent internship?",
            "How do you prioritize your tasks when you have multiple exams or projects?",
            "Describe a situation where you had to work with someone very different from you.",
            "What is your understanding of our company culture?",
            "Where do you see yourself in five years within this industry?",
            "How do you handle technical challenges without much professional experience?",
            "What motivated you to choose your current major?",
            "How do you plan to contribute to our team's success?"
        ],
        'Company Switch' => [
            "What specific values are you looking for in your next employer?",
            "How will your previous experience translate to our specific industry?",
            "Tell me about a time you improved a process at your current job.",
            "What is the biggest risk you have taken in your career so far?",
            "How do you handle the transition period when joining a new team?",
            "Why are you looking to leave your current company now?",
            "What are you looking for in this role that you don't have in your current one?",
            "Describe your most significant professional achievement.",
            "How do you handle being the 'new person' in an established team?",
            "What is your approach to learning a new company's internal tools and culture?",
            "Describe a time you disagreed with your manager. How did you handle it?",
            "How do you handle high-pressure deadlines in your current role?",
            "What is your experience with cross-functional team collaboration?",
            "How do you stay updated with industry trends outside of your current company?",
            "What kind of work environment helps you perform at your best?",
            "How do you handle a situation where your project's scope suddenly changes?",
            "Describe a time you had to mentor or train a colleague.",
            "What is your strategy for the first 90 days in this new position?",
            "How do you maintain professional relationships after leaving a company?",
            "What is the most valuable feedback you've received in your career?"
        ],
        'Masters Interview' => [
            "What specific research gap do you aim to address in your Master's studies?",
            "How does this specific university align with your academic aspirations?",
            "Describe your experience with academic writing and peer review.",
            "How do you plan to contribute to the university's research community?",
            "What is your long-term vision for your academic career?",
            "Why did you choose this particular specialization for your Master's?",
            "How will this degree help you achieve your career objectives?",
            "Describe a research project you've worked on during your undergraduate years.",
            "How do you handle the rigors of advanced academic study and research?",
            "What are your views on the current state of research in your chosen field?",
            "How do you plan to fund your Master's degree?",
            "Describe a time you had to synthesize large amounts of complex information.",
            "How do you stay motivated during long and difficult research phases?",
            "What is the importance of networking in academia, in your opinion?",
            "How do you handle disagreements with professors or research advisors?",
            "What are your thoughts on interdisciplinary research?",
            "How do you plan to manage your time between coursework and research?",
            "Describe a challenging academic situation and how you overcame it.",
            "What is your experience with data analysis and statistical software?",
            "How do you plan to use your Master's degree after graduation?"
        ],
        'Skill Enhancement' => [
            "Which specific skill do you believe is currently the most critical in your field?",
            "How do you measure the ROI of the time you spend on self-improvement?",
            "Describe a time you taught yourself a complex skill without formal training.",
            "How do you filter through the noise to find quality learning resources?",
            "What is your current 'learning roadmap' for the next 12 months?",
            "How do you apply newly learned skills to your current work or projects?",
            "What motivated you to start this journey of skill enhancement?",
            "How do you handle the 'plateau effect' when learning a new skill?",
            "Describe a time you failed to master a skill. What did you learn from it?",
            "How do you find mentors or communities to help you in your learning?",
            "What is the role of persistence in skill development?",
            "How do you balance learning new things with maintaining your existing skills?",
            "What are the challenges of learning while working full-time?",
            "How do you document or showcase your progress as you learn?",
            "What is the most rewarding part of mastering a new skill?",
            "How do you stay updated as the skills required in your field evolve?",
            "What is your approach to deep work and focused learning?",
            "How do you handle the feeling of being overwhelmed by how much there is to learn?",
            "Describe a time you used a new skill to solve a real-world problem.",
            "What is the next big skill on your list to master?"
        ]
    ],
    'education' => [
        'UG' => [
            "Tell me about a group project where you had to resolve a conflict.",
            "What subjects did you find most challenging and why?",
            "How do you balance your academics with extracurricular activities?",
            "What motivated you to choose your current major?",
            "Describe a time you showed initiative in your college life.",
            "What is the most interesting thing you've learned in your degree so far?",
            "How do you handle exam stress and tight deadlines?",
            "Describe your experience with internships or volunteer work.",
            "What are your plans for immediately after you graduate?",
            "How do you stay organized with multiple assignments and projects?",
            "Describe a time you had to work with a teammate who wasn't contributing.",
            "What role do you usually take in a team setting?",
            "How do you approach a subject that you find boring or difficult?",
            "What is your favorite memory from your time in university so far?",
            "How has college changed your perspective on your future career?",
            "What soft skills have you developed during your undergraduate studies?",
            "Describe an project you are particularly proud of.",
            "How do you handle feedback from professors and mentors?",
            "What is the biggest challenge you've faced during your degree?",
            "Why did you choose this specific university or college?"
        ],
        'PG' => [
            "How does your postgraduate specialization differentiate you in the market?",
            "Describe your thesis/dissertation topic in simple terms.",
            "How have your career goals evolved since your undergraduate studies?",
            "What advanced research methodologies are you most proficient in?",
            "Tell me about a time you led a research team or project.",
            "What is the most significant contribution your PG work makes to the field?",
            "How do you balance specialized study with a broad industry perspective?",
            "Describe a complex problem you solved during your postgraduate studies.",
            "How do you stay at the forefront of research in your specialization?",
            "What motivated you to pursue a postgraduate degree instead of working immediately?",
            "How has your PG experience changed your approach to problem-solving?",
            "Describe your experience with interdisciplinary collaboration at the PG level.",
            "What are the challenges of conducting original research?",
            "How do you handle the pressure of presenting your work at conferences or seminars?",
            "What is your long-term vision for your career following your PG degree?",
            "How do you manage the higher workload and expectations of a PG program?",
            "What soft skills have you refined during your postgraduate studies?",
            "Describe a time you had to pivot your research or project direction.",
            "How do you handle negative peer reviews or criticism of your work?",
            "What is the value of your specialization in the current global market?"
        ],
        'Employee' => [
            "How do you maintain a work-life balance in a demanding role?",
            "Describe a time you had to mentor a junior team member.",
            "What is your strategy for staying relevant in an evolving industry?",
            "How do you handle high-pressure decision-making situations?",
            "Tell me about a time you had to manage a project with limited resources.",
            "How do you approach conflict resolution with a colleague or manager?",
            "What is the most significant impact you've had on your current company?",
            "How do you stay motivated and avoid burnout in your career?",
            "Describe your approach to professional networking and relationship building.",
            "What is your experience with cross-functional collaboration in a corporate setting?",
            "How do you handle a situation where you disagree with a company policy?",
            "What are the most important skills you've developed in your professional life?",
            "How do you stay updated with industry-wide best practices?",
            "Describe a time you had to lead a team through a period of change.",
            "How do you handle being given a task that is outside of your comfort zone?",
            "What is your philosophy on leadership and management?",
            "How do you measure your own success in your professional role?",
            "Describe your experience with budget management or resource allocation.",
            "How do you approach long-term career planning and goal setting?",
            "What makes you a valuable asset to any team you join?"
        ],
        'Speaker' => [
            "How do you tailor your communication style for different audiences?",
            "Describe a time a presentation didn't go as planned and how you recovered.",
            "What is your process for researching and preparing a new keynote?",
            "How do you handle difficult questions from a live audience?",
            "Tell me about a time you had to captivate a disengaged audience.",
            "What are the most important elements of a compelling presentation?",
            "How do you use storytelling to convey complex ideas?",
            "What is your approach to stage presence and non-verbal communication?",
            "How do you measure the impact and success of your speaking engagements?",
            "Describe your experience with different presentation technologies and tools.",
            "How do you stay calm and focused before a major presentation?",
            "What is the most challenging feedback you've received as a speaker?",
            "How do you build and maintain your personal brand as a speaker?",
            "Describe a time you had to adapt your content on the fly during a talk.",
            "How do you handle different cultural sensitivities when speaking globally?",
            "What is your strategy for networking with audience members and organizers?",
            "How do you use humor or emotion to connect with your audience?",
            "Describe your process for continuous improvement as an orator.",
            "What is the most rewarding speaking experience you've had?",
            "How do you see the future of public speaking in a virtual or hybrid world?"
        ]
    ],
    'general' => [
        "Tell me about yourself and your journey so far.",
        "What are your three greatest strengths and one major weakness?",
        "Describe a significant failure and what you learned from it.",
        "Where do you see yourself in five years?",
        "Why should we choose you over other qualified candidates?",
        "How do you define success in your professional life?",
        "What motivates you to do your best work every day?",
        "Describe a time you had to work with a difficult person. How did you handle it?",
        "How do you handle stress and pressure?",
        "What are your salary expectations for this role?",
        "Tell me about a time you showed leadership, even if you weren't in a formal role.",
        "What do you know about our company and why do you want to work here?",
        "How do you handle multiple priorities and stay organized?",
        "What is your favorite book or podcast, and how has it influenced you?",
        "Tell me about a time you went above and beyond what was expected of you.",
        "What are you passionate about outside of work?",
        "How do you handle constructive criticism?",
        "Describe a situation where you had to learn something very quickly.",
        "What is your proudest professional or academic achievement?",
        "If you could have dinner with any historical figure, who would it be and why?"
    ]
];
